//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsTacticsBoard.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SportsTacticsBoard.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CurrentLayoutNumber_Empty {
            get {
                return ResourceManager.GetString("CurrentLayoutNumber_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}/{1}.
        /// </summary>
        internal static string CurrentLayoutNumber_Format {
            get {
                return ResourceManager.GetString("CurrentLayoutNumber_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The custom label is longer than recommended (2 characters or less). It probably won&apos;t display properly. Do you want to keep this label?.
        /// </summary>
        internal static string CustomLabelLongerThanRecommended {
            get {
                return ResourceManager.GetString("CustomLabelLongerThanRecommended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DataContainer_MoveFirstHS {
            get {
                object obj = ResourceManager.GetObject("DataContainer_MoveFirstHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DataContainer_MoveLastHS {
            get {
                object obj = ResourceManager.GetObject("DataContainer_MoveLastHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DataContainer_MoveNextHS {
            get {
                object obj = ResourceManager.GetObject("DataContainer_MoveNextHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DataContainer_MovePreviousHS {
            get {
                object obj = ResourceManager.GetObject("DataContainer_MovePreviousHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DeleteHS {
            get {
                object obj = ResourceManager.GetObject("DeleteHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Edit_UndoHS {
            get {
                object obj = ResourceManager.GetObject("Edit_UndoHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout field type tag is not valid.
        /// </summary>
        internal static string ExceptionMessage_LayoutFieldTagInvalid {
            get {
                return ResourceManager.GetString("ExceptionMessage_LayoutFieldTagInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout name is not valid.
        /// </summary>
        internal static string ExceptionMessage_LayoutNameInvalid {
            get {
                return ResourceManager.GetString("ExceptionMessage_LayoutNameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to open file {0}.
        /// </summary>
        internal static string FailedToOpenFileFormatStr {
            get {
                return ResourceManager.GetString("FailedToOpenFileFormatStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ball.
        /// </summary>
        internal static string FieldObject_Ball {
            get {
                return ResourceManager.GetString("FieldObject_Ball", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C{0}.
        /// </summary>
        internal static string FieldObject_BaseCone_Label_Format {
            get {
                return ResourceManager.GetString("FieldObject_BaseCone_Label_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cone - {0}.
        /// </summary>
        internal static string FieldObject_BaseCone_Name_Format {
            get {
                return ResourceManager.GetString("FieldObject_BaseCone_Name_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player.
        /// </summary>
        internal static string FieldObject_Player {
            get {
                return ResourceManager.GetString("FieldObject_Player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player - {0} - {1}.
        /// </summary>
        internal static string FieldObject_Player_Name_Format {
            get {
                return ResourceManager.GetString("FieldObject_Player_Name_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puck.
        /// </summary>
        internal static string FieldObject_Puck {
            get {
                return ResourceManager.GetString("FieldObject_Puck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referee 1.
        /// </summary>
        internal static string FieldObject_Referee_Futsal_1 {
            get {
                return ResourceManager.GetString("FieldObject_Referee_Futsal_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referee 2.
        /// </summary>
        internal static string FieldObject_Referee_Futsal_2 {
            get {
                return ResourceManager.GetString("FieldObject_Referee_Futsal_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referee 1.
        /// </summary>
        internal static string FieldObject_Referee_Handball_1 {
            get {
                return ResourceManager.GetString("FieldObject_Referee_Handball_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referee 2.
        /// </summary>
        internal static string FieldObject_Referee_Handball_2 {
            get {
                return ResourceManager.GetString("FieldObject_Referee_Handball_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referee 1.
        /// </summary>
        internal static string FieldObject_Referee_Hockey_1 {
            get {
                return ResourceManager.GetString("FieldObject_Referee_Hockey_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referee 2.
        /// </summary>
        internal static string FieldObject_Referee_Hockey_2 {
            get {
                return ResourceManager.GetString("FieldObject_Referee_Hockey_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linesman 1.
        /// </summary>
        internal static string FieldObject_Referee_Hockey_L1 {
            get {
                return ResourceManager.GetString("FieldObject_Referee_Hockey_L1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linesman 2.
        /// </summary>
        internal static string FieldObject_Referee_Hockey_L2 {
            get {
                return ResourceManager.GetString("FieldObject_Referee_Hockey_L2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referee - 4th Official.
        /// </summary>
        internal static string FieldObject_Referee_Soccer_4th {
            get {
                return ResourceManager.GetString("FieldObject_Referee_Soccer_4th", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referee - Assistant #1.
        /// </summary>
        internal static string FieldObject_Referee_Soccer_AR1 {
            get {
                return ResourceManager.GetString("FieldObject_Referee_Soccer_AR1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referee - Assistant #2.
        /// </summary>
        internal static string FieldObject_Referee_Soccer_AR2 {
            get {
                return ResourceManager.GetString("FieldObject_Referee_Soccer_AR2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referee - Centre.
        /// </summary>
        internal static string FieldObject_Referee_Soccer_CR {
            get {
                return ResourceManager.GetString("FieldObject_Referee_Soccer_CR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referee - Main.
        /// </summary>
        internal static string FieldObject_Referee_Volleyball_N {
            get {
                return ResourceManager.GetString("FieldObject_Referee_Volleyball_N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referee - Line #2.
        /// </summary>
        internal static string FieldObject_Referee_Volleyball_NE {
            get {
                return ResourceManager.GetString("FieldObject_Referee_Volleyball_NE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referee - Line #1.
        /// </summary>
        internal static string FieldObject_Referee_Volleyball_NW {
            get {
                return ResourceManager.GetString("FieldObject_Referee_Volleyball_NW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referee - Assistant.
        /// </summary>
        internal static string FieldObject_Referee_Volleyball_S {
            get {
                return ResourceManager.GetString("FieldObject_Referee_Volleyball_S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referee - Line #4.
        /// </summary>
        internal static string FieldObject_Referee_Volleyball_SE {
            get {
                return ResourceManager.GetString("FieldObject_Referee_Volleyball_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referee - Line #3.
        /// </summary>
        internal static string FieldObject_Referee_Volleyball_SW {
            get {
                return ResourceManager.GetString("FieldObject_Referee_Volleyball_SW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floorball.
        /// </summary>
        internal static string FieldType_Floorball {
            get {
                return ResourceManager.GetString("FieldType_Floorball", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Futsal (FIFA).
        /// </summary>
        internal static string FieldType_Futsal {
            get {
                return ResourceManager.GetString("FieldType_Futsal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handball.
        /// </summary>
        internal static string FieldType_Handball {
            get {
                return ResourceManager.GetString("FieldType_Handball", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ice Hockey (NHL).
        /// </summary>
        internal static string FieldType_Hockey_NHL {
            get {
                return ResourceManager.GetString("FieldType_Hockey_NHL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to American Football (NFL).
        /// </summary>
        internal static string FieldType_NFLFootball {
            get {
                return ResourceManager.GetString("FieldType_NFLFootball", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Football/Soccer (FIFA).
        /// </summary>
        internal static string FieldType_Soccer {
            get {
                return ResourceManager.GetString("FieldType_Soccer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Football/Soccer 5 vs 5.
        /// </summary>
        internal static string FieldType_Soccer5 {
            get {
                return ResourceManager.GetString("FieldType_Soccer5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Football/Soccer 7 vs 7.
        /// </summary>
        internal static string FieldType_Soccer7 {
            get {
                return ResourceManager.GetString("FieldType_Soccer7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Football/Soccer 9 vs 9.
        /// </summary>
        internal static string FieldType_Soccer9 {
            get {
                return ResourceManager.GetString("FieldType_Soccer9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volleyball.
        /// </summary>
        internal static string FieldType_Volleyball {
            get {
                return ResourceManager.GetString("FieldType_Volleyball", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sports Tactics Board files (*.stb.xml)|*.stb.xml|All files (*.*)|*.*.
        /// </summary>
        internal static string FileFilter {
            get {
                return ResourceManager.GetString("FileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GoToNextHS {
            get {
                object obj = ResourceManager.GetObject("GoToNextHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GoToPrevious {
            get {
                object obj = ResourceManager.GetObject("GoToPrevious", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Help {
            get {
                object obj = ResourceManager.GetObject("Help", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - {0:000}.
        /// </summary>
        internal static string ImageFileNamePattern {
            get {
                return ResourceManager.GetString("ImageFileNamePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value supplied (&apos;{1}&apos;) for {0} option does not contain a valid or supported value.
        /// </summary>
        internal static string InvalidCultureOption_Format {
            get {
                return ResourceManager.GetString("InvalidCultureOption_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Parameters.
        /// </summary>
        internal static string InvalidParametersTitle {
            get {
                return ResourceManager.GetString("InvalidParametersTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} option missing culture name.
        /// </summary>
        internal static string MissingCultureOptionValue_Format {
            get {
                return ResourceManager.GetString("MissingCultureOptionValue_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NavBack {
            get {
                object obj = ResourceManager.GetObject("NavBack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NavForward {
            get {
                object obj = ResourceManager.GetObject("NavForward", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NewDocumentHS {
            get {
                object obj = ResourceManager.GetObject("NewDocumentHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;&lt;none&gt;&gt;.
        /// </summary>
        internal static string NoSavedLayoutsMenuItemText {
            get {
                return ResourceManager.GetString("NoSavedLayoutsMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not implemented yet!.
        /// </summary>
        internal static string NotImplementedYet {
            get {
                return ResourceManager.GetString("NotImplementedYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap openHS {
            get {
                object obj = ResourceManager.GetObject("openHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PauseHS {
            get {
                object obj = ResourceManager.GetObject("PauseHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PlayHS {
            get {
                object obj = ResourceManager.GetObject("PlayHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RecordHS {
            get {
                object obj = ResourceManager.GetObject("RecordHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RepeatHS {
            get {
                object obj = ResourceManager.GetObject("RepeatHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RestartHS {
            get {
                object obj = ResourceManager.GetObject("RestartHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Bitmap (BMP)|*.bmp|Graphics Interchange Format (GIF)|*.gif|Portable Network Graphics (PNG)|*.png|Joint Photographic Experts Group (JPEG)|*.jpg.
        /// </summary>
        internal static string SaveAsImageFileFilter {
            get {
                return ResourceManager.GetString("SaveAsImageFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one item must be checked..
        /// </summary>
        internal static string SavedLayoutInformation_ErrorMessage_AtLeastOneItemMustBeChecked {
            get {
                return ResourceManager.GetString("SavedLayoutInformation_ErrorMessage_AtLeastOneItemMustBeChecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name must not be blank..
        /// </summary>
        internal static string SavedLayoutInformation_ErrorMessage_NameMustNotBeBlank {
            get {
                return ResourceManager.GetString("SavedLayoutInformation_ErrorMessage_NameMustNotBeBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap saveHS {
            get {
                object obj = ResourceManager.GetObject("saveHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As Image File.
        /// </summary>
        internal static string SaveImageDialogTitle {
            get {
                return ResourceManager.GetString("SaveImageDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Sequence As Image Files.
        /// </summary>
        internal static string SaveImageSequenceDialogTitle {
            get {
                return ResourceManager.GetString("SaveImageSequenceDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save your current layout in place of the current sequence entry?.
        /// </summary>
        internal static string SaveSequenceEntryBeforeSwitchingEntries {
            get {
                return ResourceManager.GetString("SaveSequenceEntryBeforeSwitchingEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attacking.
        /// </summary>
        internal static string TeamName_Attacking {
            get {
                return ResourceManager.GetString("TeamName_Attacking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defending.
        /// </summary>
        internal static string TeamName_Defending {
            get {
                return ResourceManager.GetString("TeamName_Defending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - {1}.
        /// </summary>
        internal static string TitleFormatString {
            get {
                return ResourceManager.GetString("TitleFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to locate document. The installation of this program may not be complete or may have been modified..
        /// </summary>
        internal static string UnableToOpenFile_InstallationMayBeIncomplete {
            get {
                return ResourceManager.GetString("UnableToOpenFile_InstallationMayBeIncomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] zoom {
            get {
                object obj = ResourceManager.GetObject("zoom", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
